### ISSUE TITLE
[Bug] - Re-adding removed assets into category fails and errors the user out

### ISSUE THREAD

**Issue by mohit2530** [earmuff-jam/pulse#278]
# Acceptance Criteria

1. When the user removes item association for any asset, and attempts to re-add it to the system, the application fails with foriegn-key constraint failure in db. Investigate why.

**Comment by earmuff-jam** [comment]
Testing steps 

1. `Add asset` to category or maintenance plan.
2. Remove the selected `asset` from the category or maintenance plan.
3. Re-add the `asset`.
4. Notice the failure.
