### ISSUE TITLE
Fails to display new image from Grid Component

### ISSUE THREAD

**Issue by mohit2530** [earmuff-jam/pulse#305]
Given that the user is a valid user
And when the said user is trying to view the asset list via grid component
And when the said user adds a new image to the selected asset
The image does not immediately display in the screen. Rather the user has to refresh the page.

# Acceptance Criteria
1. The user must not have to refresh the page to view the image that they just added for the selected component.

## Technical Details

Although this can be done in one of several ways, the efficient strategy here that we are planning to leverage is that after the dispatch action for updating the image for the asset detail occurs, we retrieve the list of assets via saga since they have generator methods (yield) 
to allow us to fetch the inventory list.

We could use the same image and populate the selected asset, but that would require more data manipulation from the UI. Instead we just simply re - fetch the data via saga.

**Comment by earmuff-jam** [comment]
Completed the work for this issue in ticket - `292-add-category-storybook`

**Comment by mohit2530** [comment]
Also is used to fix the `selected asset` details page.
